name: ERD Online to docker
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 步骤名称
    - name: checkout code
      uses: actions/checkout@v2
    - name: actions/setup-node@v2
      uses: actions/setup-node@v2
      with:
        node-version: '14.20'
    - run: ./build.sh

  push_to_docker:  # job的名字
    needs: [build]
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest   # job运行的基础环境
    steps:  # 一个job由一个或多个step组成
      - name: Login to Registry
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Image
        run: |
          docker buildx build --platform linux/arm64,linux/amd64 -t erdonline/erd-ui:latest -f ci/Dockerfile . --push
          docker buildx build --platform linux/arm64,linux/amd64 -t erdonline/erd-ui:4.0.6 -f ci/Dockerfile . --push
