name: ERD Online to docker
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAG: 4.0.6
    steps:
    # 步骤名称
    - name: checkout code
      uses: actions/checkout@v2
    - name: actions/setup-node@v2
      uses: actions/setup-node@v2
      with:
        node-version: '14.20'
    - run: ./build.sh
    - name: Log in to Docker Hub
      uses: docker/login-action@v1  # 三方的action操作， 执行docker login
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}  # 配置dockerhub的认证，在Github项目主页 【Settings】 -> 【Secrets】 添加对应变量
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Image
      run: |
        docker buildx create --name mybuilder --driver docker-container --use
        docker buildx build --platform linux/arm64,linux/amd64 -t erdonline/erd-ui:latest -f ci/Dockerfile . --push
        docker buildx build --platform linux/arm64,linux/amd64 -t erdonline/erd-ui:${{ env.TAG }} -f ci/Dockerfile . --push
