name: github public ip
on:
  push:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        #需要部署的文件地址
        source: 'ci/*'
        strip_components: 1
        # SSH address  服务器地址
        host: ${{ secrets.ERD_VM_HOST }}
        # Remote dir path  服务器下部署文件存放路径
        target: ${{ secrets.ERD_VM_REMOTE_PATH }}
        # SSH Port  服务器端口
        port: ${{ secrets.ERD_VM_PORT }}
        # SSH User name   用户名
        username: ${{ secrets.ERD_VM_HOST_USERNAME }}
        # SSH User password  用户密码
        #  password: ${{ secrets.PASSWORD }}
        # key  密匙
        key: ${{ secrets.ERD_VM_SSH }}

